truncate table xcx_appointment;
truncate table xcx_comment;
truncate table xcx_dynamic;
truncate table xcx_fav;
truncate table xcx_info;
truncate table xcx_msg;
truncate table xcx_notice;
truncate table xcx_user;
truncate table xcx_zan;