spring:
  datasource:
        name: test
        url: jdbc:mysql://localhost:3306/xcx?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  mybatis:
    mapper-locations: classpath:com/wang/aishenhuo/pc/api/myBatis/mapping/*.xml
    config-location: classpath:com/wang/aishenhuo/pc/api/myBatis/mybatis-config.xml
server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 100
  tomcat.uri-encoding: UTF-8  
redis-expire: 1800
page: 
  pageSize: 5
constant: 
  wx: 
    appid: wxa4a76bcefc655c8f
    secret: d5da2b0cba4777b55f5aa973f09cb00b
    jscode2session: https://api.weixin.qq.com/sns/jscode2session?
    token: https://api.weixin.qq.com/cgi-bin/token?
    send: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?